// Auto-generated by scripts/generate-env.js — do not edit manually.
// To regenerate: npm run env:generate  (add --prod for production builds)
import { Environment } from "./environment.interface";

export const environment: Environment = {
  production: false,
  auth: {
    domain: "",
    clientId: "",
    audience: "",
  },
  apiBaseUrl: "",
  profileUrl: "",
};
