#!/usr/bin/env node
// Reads .env (or process.env) and writes src/environments/environment.ts.
// Run with --prod to set production: true (used by CI before ng build).
"use strict";

const fs = require("fs");
const path = require("path");

const root = path.join(__dirname, "..");
const envFile = path.join(root, ".env");
const fileVars = {};

if (fs.existsSync(envFile)) {
  for (const raw of fs.readFileSync(envFile, "utf8").split("\n")) {
    const line = raw.trim();
    if (!line || line.startsWith("#")) continue;
    const eq = line.indexOf("=");
    if (eq === -1) continue;
    const key = line.slice(0, eq).trim();
    const val = line
      .slice(eq + 1)
      .trim()
      .replace(/^(['"])(.*)\1$/, "$2");
    fileVars[key] = val;
  }
} else {
  console.warn("[generate-env] No .env file found — using process.env only.");
}

// process.env takes precedence so CI can override via exported vars
const get = (key) => process.env[key] ?? fileVars[key] ?? "";

const isProd = process.argv.includes("--prod");

const content = `// Auto-generated by scripts/generate-env.js — do not edit manually.
// To regenerate: npm run env:generate  (add --prod for production builds)
import { Environment } from "./environment.interface";

export const environment: Environment = {
  production: ${isProd},
  auth: {
    domain: "${get("AUTH_DOMAIN")}",
    clientId: "${get("AUTH_CLIENT_ID")}",
    audience: "${get("AUTH_AUDIENCE")}",
  },
  apiBaseUrl: "${get("API_BASE_URL")}",
  profileUrl: "${get("PROFILE_URL")}",
};
`;

// Validate that mandatory fields were resolved
const missing = [
  "AUTH_DOMAIN",
  "AUTH_CLIENT_ID",
  "AUTH_AUDIENCE",
  "API_BASE_URL",
  "PROFILE_URL",
].filter((k) => !get(k));

if (missing.length) {
  console.warn(
    `[generate-env] Warning: missing values for: ${missing.join(", ")}`
  );
}

const outFile = isProd
  ? path.join(root, "src", "environments", "environment.prod.ts")
  : path.join(root, "src", "environments", "environment.ts");

fs.writeFileSync(outFile, content, "utf8");
console.log(`[generate-env] Written ${path.relative(root, outFile)}`);
